//! Rust emission for the generated client. Schema-driven: struct fields, `to_json` and
//! `from_json` are derived from the exported schema's field lists; the transport glue
//! (`negotiate`, `ClientError`) is a fixed template. Deterministic output — the same schema
//! always produces byte-identical bytes, so the CI drift check is stable.

use crate::type_fields;
use hh_wire::json::Json;
use std::fmt::Write as _;

const HEADER: &str = "\
// @generated by hh-codegen — DO NOT EDIT.
//
// Source of truth: the `hh-embed-schema` crate (the single schema source, CC7). Regenerate
// with `cargo run -p hh-codegen -- --root <repo>`; `scripts/check-drift.sh` fails the build
// if this file drifts from the schema. A generated client contains no runtime logic beyond
// the transport binding (ADR-0179): it asserts `(contract_major, schema_hash)` and lowers a
// mismatch to a typed error.
";

/// Emit the full `generated.rs` for the client crate.
pub fn generated_client(schema: &Json, schema_hash: &str) -> Result<String, String> {
    let contract_major = schema
        .get("contract_major")
        .and_then(Json::as_int)
        .ok_or("schema missing contract_major")?;

    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str("#![allow(clippy::all)]\n\n");
    s.push_str("use hh_wire::json::Json;\n");
    s.push_str("use std::io::{BufRead, Write};\n\n");

    writeln!(
        s,
        "/// The contract major this client was generated against.\npub const CONTRACT_MAJOR: i64 = {contract_major};\n"
    )
    .unwrap();
    writeln!(
        s,
        "/// The schema content address this client was generated against (`sha256:<hex>`).\npub const EXPECTED_SCHEMA_HASH: &str = {schema_hash:?};\n"
    )
    .unwrap();

    // Schema-derived types the round trip uses.
    for type_name in ["HelloParams", "ContractIdentity"] {
        emit_struct(&mut s, schema, type_name)?;
    }

    s.push_str(GLUE);
    Ok(s)
}

fn emit_struct(out: &mut String, schema: &Json, type_name: &str) -> Result<(), String> {
    let fields = type_fields(schema, type_name)?;

    // Struct definition.
    writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub struct {type_name} {{").unwrap();
    for f in fields {
        let (name, ty, required) = field_parts(f)?;
        let rust_ty = rust_type(ty, required);
        writeln!(out, "    pub {name}: {rust_ty},").unwrap();
    }
    out.push_str("}\n\n");

    // impl with to_json / from_json.
    writeln!(out, "impl {type_name} {{").unwrap();

    // to_json
    out.push_str("    pub fn to_json(&self) -> Json {\n");
    out.push_str("        let mut pairs: Vec<(&'static str, Json)> = Vec::new();\n");
    for f in fields {
        let (name, ty, required) = field_parts(f)?;
        if required {
            writeln!(
                out,
                "        pairs.push(({name:?}, {}));",
                to_json_expr(name, ty)
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "        if let Some(v) = &self.{name} {{ pairs.push(({name:?}, {})); }}",
                to_json_expr_opt(ty)
            )
            .unwrap();
        }
    }
    out.push_str("        Json::obj(pairs)\n    }\n\n");

    // from_json
    writeln!(
        out,
        "    pub fn from_json(v: &Json) -> Result<{type_name}, String> {{"
    )
    .unwrap();
    writeln!(out, "        Ok({type_name} {{").unwrap();
    for f in fields {
        let (name, ty, required) = field_parts(f)?;
        writeln!(
            out,
            "            {name}: {},",
            from_json_expr(name, ty, required)
        )
        .unwrap();
    }
    out.push_str("        })\n    }\n}\n\n");
    Ok(())
}

fn field_parts(f: &Json) -> Result<(&str, &str, bool), String> {
    let name = f
        .get("name")
        .and_then(Json::as_str)
        .ok_or("field missing name")?;
    let ty = f
        .get("type")
        .and_then(Json::as_str)
        .ok_or("field missing type")?;
    let required = matches!(f.get("required"), Some(Json::Bool(true)));
    Ok((name, ty, required))
}

fn rust_type(ty: &str, required: bool) -> String {
    let base = match ty {
        "string" => "String",
        "integer" => "i64",
        other => other, // a named type, e.g. ContractIdentity
    };
    if required {
        base.to_string()
    } else {
        format!("Option<{base}>")
    }
}

fn to_json_expr(name: &str, ty: &str) -> String {
    match ty {
        "string" => format!("Json::str(self.{name}.clone())"),
        "integer" => format!("Json::Int(self.{name})"),
        _ => format!("self.{name}.to_json()"),
    }
}

fn to_json_expr_opt(ty: &str) -> String {
    match ty {
        "string" => "Json::str(v.clone())".to_string(),
        "integer" => "Json::Int(*v)".to_string(),
        _ => "v.to_json()".to_string(),
    }
}

fn from_json_expr(name: &str, ty: &str, required: bool) -> String {
    if !required {
        return match ty {
            "string" => format!("v.get({name:?}).and_then(Json::as_str).map(|s| s.to_string())"),
            "integer" => format!("v.get({name:?}).and_then(Json::as_int)"),
            _ => format!(
                "match v.get({name:?}) {{ Some(x) => Some({ty}::from_json(x)?), None => None }}"
            ),
        };
    }
    match ty {
        "string" => format!(
            "v.get({name:?}).and_then(Json::as_str).map(|s| s.to_string()).ok_or_else(|| \"missing '{name}'\".to_string())?"
        ),
        "integer" => format!(
            "v.get({name:?}).and_then(Json::as_int).ok_or_else(|| \"missing '{name}'\".to_string())?"
        ),
        _ => format!(
            "{ty}::from_json(v.get({name:?}).ok_or_else(|| \"missing '{name}'\".to_string())?)?"
        ),
    }
}

/// The fixed transport glue: the `hello` negotiation and the typed client error sum.
const GLUE: &str = r##"/// A typed client error. A negotiation mismatch is surfaced here, never as a silent
/// fallback (ADR-0178 D2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientError {
    Transport(String),
    Rpc { code: i64, kind: String, message: String },
    IdentityMismatch { field: String },
}

/// Drive one `hello` negotiation over a newline-delimited JSON-RPC 2.0 stream (binding (b)).
/// Asserts `(contract_major, schema_hash)` against the kernel's returned identity.
pub fn negotiate<R: BufRead, W: Write>(
    reader: &mut R,
    writer: &mut W,
    client_name: &str,
    client_version: &str,
) -> Result<ContractIdentity, ClientError> {
    let params = HelloParams {
        client_name: client_name.to_string(),
        client_version: client_version.to_string(),
        asserted_contract_major: CONTRACT_MAJOR,
        asserted_schema_hash: Some(EXPECTED_SCHEMA_HASH.to_string()),
    };
    let req = Json::obj([
        ("jsonrpc", Json::str("2.0")),
        ("id", Json::Int(1)),
        ("method", Json::str("hello")),
        ("params", params.to_json()),
    ]);
    let mut line = req.to_canonical_string();
    line.push('\n');
    writer
        .write_all(line.as_bytes())
        .map_err(|e| ClientError::Transport(e.to_string()))?;
    writer
        .flush()
        .map_err(|e| ClientError::Transport(e.to_string()))?;

    let mut resp_line = String::new();
    let n = reader
        .read_line(&mut resp_line)
        .map_err(|e| ClientError::Transport(e.to_string()))?;
    if n == 0 {
        return Err(ClientError::Transport("kernel closed the stream".to_string()));
    }
    let resp = hh_wire::parse(resp_line.trim())
        .map_err(|e| ClientError::Transport(e.to_string()))?;

    if let Some(err) = resp.get("error") {
        let code = err.get("code").and_then(Json::as_int).unwrap_or(0);
        let kind = err
            .get("data")
            .and_then(|d| d.get("kind"))
            .and_then(Json::as_str)
            .unwrap_or("Unknown")
            .to_string();
        let message = err
            .get("message")
            .and_then(Json::as_str)
            .unwrap_or("")
            .to_string();
        return Err(ClientError::Rpc { code, kind, message });
    }

    let ci_json = resp
        .get("result")
        .and_then(|r| r.get("contract_identity"))
        .ok_or_else(|| ClientError::Transport("missing result.contract_identity".to_string()))?;
    let ci = ContractIdentity::from_json(ci_json).map_err(ClientError::Transport)?;

    if ci.contract_major != CONTRACT_MAJOR {
        return Err(ClientError::IdentityMismatch {
            field: "contract_major".to_string(),
        });
    }
    if ci.schema_hash != EXPECTED_SCHEMA_HASH {
        return Err(ClientError::IdentityMismatch {
            field: "schema_hash".to_string(),
        });
    }
    Ok(ci)
}
"##;
