// @generated by hh-codegen — DO NOT EDIT.
//
// Source of truth: the `hh-embed-schema` crate (the single schema source, CC7). Regenerate
// with `cargo run -p hh-codegen -- --root <repo>`; `scripts/check-drift.sh` fails the build
// if this file drifts from the schema. A generated client contains no runtime logic beyond
// the transport binding (ADR-0179): it asserts `(contract_major, schema_hash)` and lowers a
// mismatch to a typed error.

#![allow(clippy::all)]

use hh_wire::json::Json;
use std::io::{BufRead, Write};

/// The contract major this client was generated against.
pub const CONTRACT_MAJOR: i64 = 1;

/// The schema content address this client was generated against (`sha256:<hex>`).
pub const EXPECTED_SCHEMA_HASH: &str =
    "sha256:fbbf02de4ff017994380564938011118918cdf4e3fedadbfd30d8a35f37e3757";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HelloParams {
    pub client_name: String,
    pub client_version: String,
    pub asserted_contract_major: i64,
    pub asserted_schema_hash: Option<String>,
}

impl HelloParams {
    pub fn to_json(&self) -> Json {
        let mut pairs: Vec<(&'static str, Json)> = Vec::new();
        pairs.push(("client_name", Json::str(self.client_name.clone())));
        pairs.push(("client_version", Json::str(self.client_version.clone())));
        pairs.push((
            "asserted_contract_major",
            Json::Int(self.asserted_contract_major),
        ));
        if let Some(v) = &self.asserted_schema_hash {
            pairs.push(("asserted_schema_hash", Json::str(v.clone())));
        }
        Json::obj(pairs)
    }

    pub fn from_json(v: &Json) -> Result<HelloParams, String> {
        Ok(HelloParams {
            client_name: v
                .get("client_name")
                .and_then(Json::as_str)
                .map(|s| s.to_string())
                .ok_or_else(|| "missing 'client_name'".to_string())?,
            client_version: v
                .get("client_version")
                .and_then(Json::as_str)
                .map(|s| s.to_string())
                .ok_or_else(|| "missing 'client_version'".to_string())?,
            asserted_contract_major: v
                .get("asserted_contract_major")
                .and_then(Json::as_int)
                .ok_or_else(|| "missing 'asserted_contract_major'".to_string())?,
            asserted_schema_hash: v
                .get("asserted_schema_hash")
                .and_then(Json::as_str)
                .map(|s| s.to_string()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContractIdentity {
    pub contract_major: i64,
    pub schema_hash: String,
    pub kernel_version_id: String,
}

impl ContractIdentity {
    pub fn to_json(&self) -> Json {
        let mut pairs: Vec<(&'static str, Json)> = Vec::new();
        pairs.push(("contract_major", Json::Int(self.contract_major)));
        pairs.push(("schema_hash", Json::str(self.schema_hash.clone())));
        pairs.push((
            "kernel_version_id",
            Json::str(self.kernel_version_id.clone()),
        ));
        Json::obj(pairs)
    }

    pub fn from_json(v: &Json) -> Result<ContractIdentity, String> {
        Ok(ContractIdentity {
            contract_major: v
                .get("contract_major")
                .and_then(Json::as_int)
                .ok_or_else(|| "missing 'contract_major'".to_string())?,
            schema_hash: v
                .get("schema_hash")
                .and_then(Json::as_str)
                .map(|s| s.to_string())
                .ok_or_else(|| "missing 'schema_hash'".to_string())?,
            kernel_version_id: v
                .get("kernel_version_id")
                .and_then(Json::as_str)
                .map(|s| s.to_string())
                .ok_or_else(|| "missing 'kernel_version_id'".to_string())?,
        })
    }
}

/// A typed client error. A negotiation mismatch is surfaced here, never as a silent
/// fallback (ADR-0178 D2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientError {
    Transport(String),
    Rpc {
        code: i64,
        kind: String,
        message: String,
    },
    IdentityMismatch {
        field: String,
    },
}

/// Drive one `hello` negotiation over a newline-delimited JSON-RPC 2.0 stream (binding (b)).
/// Asserts `(contract_major, schema_hash)` against the kernel's returned identity.
pub fn negotiate<R: BufRead, W: Write>(
    reader: &mut R,
    writer: &mut W,
    client_name: &str,
    client_version: &str,
) -> Result<ContractIdentity, ClientError> {
    let params = HelloParams {
        client_name: client_name.to_string(),
        client_version: client_version.to_string(),
        asserted_contract_major: CONTRACT_MAJOR,
        asserted_schema_hash: Some(EXPECTED_SCHEMA_HASH.to_string()),
    };
    let req = Json::obj([
        ("jsonrpc", Json::str("2.0")),
        ("id", Json::Int(1)),
        ("method", Json::str("hello")),
        ("params", params.to_json()),
    ]);
    let mut line = req.to_canonical_string();
    line.push('\n');
    writer
        .write_all(line.as_bytes())
        .map_err(|e| ClientError::Transport(e.to_string()))?;
    writer
        .flush()
        .map_err(|e| ClientError::Transport(e.to_string()))?;

    let mut resp_line = String::new();
    let n = reader
        .read_line(&mut resp_line)
        .map_err(|e| ClientError::Transport(e.to_string()))?;
    if n == 0 {
        return Err(ClientError::Transport(
            "kernel closed the stream".to_string(),
        ));
    }
    let resp =
        hh_wire::parse(resp_line.trim()).map_err(|e| ClientError::Transport(e.to_string()))?;

    if let Some(err) = resp.get("error") {
        let code = err.get("code").and_then(Json::as_int).unwrap_or(0);
        let kind = err
            .get("data")
            .and_then(|d| d.get("kind"))
            .and_then(Json::as_str)
            .unwrap_or("Unknown")
            .to_string();
        let message = err
            .get("message")
            .and_then(Json::as_str)
            .unwrap_or("")
            .to_string();
        return Err(ClientError::Rpc {
            code,
            kind,
            message,
        });
    }

    let ci_json = resp
        .get("result")
        .and_then(|r| r.get("contract_identity"))
        .ok_or_else(|| ClientError::Transport("missing result.contract_identity".to_string()))?;
    let ci = ContractIdentity::from_json(ci_json).map_err(ClientError::Transport)?;

    if ci.contract_major != CONTRACT_MAJOR {
        return Err(ClientError::IdentityMismatch {
            field: "contract_major".to_string(),
        });
    }
    if ci.schema_hash != EXPECTED_SCHEMA_HASH {
        return Err(ClientError::IdentityMismatch {
            field: "schema_hash".to_string(),
        });
    }
    Ok(ci)
}
