#!/usr/bin/env bash
# S2 boundary-crossing spike runner — the S0.1 first measurement of AC-R-2.11.4-9.
# Builds the persistent kernel + codegen (release), runs the throwaway spike, and writes a
# stamped measurement sheet to docs/build/measurements/. The full comparative spike (E5a/E5b/
# E5c) and the ADR-0050 amendment-log append are S0.3 (see the S0.1 DEFERRALS row).
set -euo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel)}"
cd "$ROOT"
SHEET="$ROOT/docs/build/measurements/S0.1-boundary-spike.md"
mkdir -p "$(dirname "$SHEET")"

echo "spike: building release kernel + codegen…"
cargo build -q --release -p hh-kernel -p hh-codegen

KERNEL="$ROOT/target/release/hh-kernel"
CODEGEN="$ROOT/target/release/hh-codegen"

echo "spike: measuring per-crossing overhead over stdio…"
RAW="$(cargo run -q --release --manifest-path spikes/s2-boundary-spike/Cargo.toml -- "$KERNEL" "$CODEGEN")"

get() { echo "$RAW" | awk -v k="$1" '$1==k {print $2}'; }

HOST="$(uname -sm)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo 'uncommitted')"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$SHEET" <<EOF
<!-- Generated by scripts/spike-s2-boundary.sh. The S0.1 first measurement of AC-R-2.11.4-9
     (§7.4; §10.6 S2 boundary slice). Internal tier-B measurement — supports no claim outside
     the ADR-0009 matrix (ADR-0050 R1–R6). Numbers vary by host and are not a gate threshold. -->
# S0.1 — S2 boundary-crossing first measurement (AC-R-2.11.4-9)

- **when:** $DATE
- **commit:** $COMMIT
- **host:** $HOST
- **binding:** (b) subprocess over stdio, newline-delimited JSON-RPC 2.0 (ADR-0179 D1(b))
- **workload:** \`$(get crossings)\` \`hello\` crossings over one persistent \`hh-kernel serve\` process, generated client

| measurement (§10.6) | value |
|---|---|
| M-S2-1 per-crossing overhead, min (µs) | $(get per_crossing_overhead_us_min) |
| M-S2-1 per-crossing overhead, median (µs) | $(get per_crossing_overhead_us_median) |
| M-S2-1 per-crossing overhead, p95 (µs) | $(get per_crossing_overhead_us_p95) |
| M-S2-1 per-crossing overhead, max (µs) | $(get per_crossing_overhead_us_max) |
| M-S2-3 codegen round-trip (ms) | $(get codegen_round_trip_ms) |
| M-S2-7 far-side hash-equality (%) | $(get hash_equality_pct) |
| durable-frame delivery latency p50 (µs) | $(get durable_frame_latency_p50_us) |
| durable-frame delivery latency p95 (µs) | $(get durable_frame_latency_p95_us) |
| ephemeral-drop rate | $(get ephemeral_drop_rate) |

**Scope note.** Durable-frame latency and ephemeral-drop are \`n/a{stage_0_no_stream}\`: the
Group R event stream lands at Stage 1, so there are no durable frames to time at Stage 0. The
S0.1 DEFERRALS row (V) tracks completing those columns and the comparative E5a/E5b/E5c spike at
S0.3, whose sheet is what appends to the ADR-0050 amendment log (OQ-131).
EOF

echo "spike: wrote $SHEET"
echo "$RAW"
